const COLLECTION_FETCH_REQUEST = 'COLLECTION_FETCH_REQUEST';
const COLLECTION_FETCH_SUCCESS = 'COLLECTION_FETCH_SUCCESS';
const COLLECTION_FETCH_ERROR = 'COLLECTION_FETCH_ERROR';

const COLLECTION_TYPE_CHANGE = 'COLLECTION_TYPES_CHANGE';
const COLLECTION_FILTER_REQUEST = 'COLLECTION_FILTER_REQUEST';

export default {
  COLLECTION_FETCH_REQUEST,
  COLLECTION_FETCH_SUCCESS,
  COLLECTION_FETCH_ERROR,
  COLLECTION_TYPE_CHANGE,
  COLLECTION_FILTER_REQUEST,
};
