type TeaCollection {
  id: ID!
  name: String!
  user: User
  teas: [Tea]
}

input TeaCollectionInput {
  id: ID!
  name: String!
  teas: [TeaInput]
}

type Query {
  teaCollections: [TeaCollection]
  userTeaCollection(colletionName: String): TeaCollection
}
